Add Google OIDC
traefik/hub-helm-chart pull request #57
Opened 2022-09-06 08:56 UTC by LandryBe

### Description

This PR adds Google OIDC CRD
Co-authored-by: Tom Moulard <tom.moulard@traefik.io>

2022-09-12 14:19 UTC, jspdown requested changes

2022-09-12 14:19 UTC, jspdown commented on hub-agent/crds/access-control-policy.yaml
> +                        has enough information to retrieve secret in any namespace
```suggestion
                        has enough information to retrieve secret in any namespace.
```

2022-09-13 08:15 UTC, jbdoumenjou approved these changes

2022-09-14 13:58 UTC, jspdown approved these changes

2022-09-14 14:00 UTC, merged