feat: Reasonable default domain for tunnelhost
traefik/hub-helm-chart pull request #77
Opened 2023-02-23 09:06 UTC by project0

### What does this PR do?

People installing the helm chart into another namespace then we usually document may experience hidden issues.
The current default values are very opiniated and assume the helm chart will be installed in "hub-agent".

In a default kubernetes cluster the dns resolution is usually able to leverage the search domain to reach services in the same namespace without knowing the fqdn.

### Motivation

Ease the installation into another namespace without setting any values (or installing along an existing traefik proxy). I had to troubleshoot a bit to understand why a published service timeout, this might help other people to get started quickly.

### More

- [ ] Yes, I updated the tests accordingly
- [ ] Yes, I ran `make test` and all the tests passed

2023-02-23 09:18 UTC, mloiseleur approved these changes

2023-02-23 09:35 UTC, svx approved these changes

2023-03-21 10:44 UTC, youkoulayley requested changes

2023-03-21 10:44 UTC, youkoulayley commented on hub-agent/values.yaml
Traefik is not necessarily deployed in the same namespace as Hub, since it's installed with the Traefik Helm Chart.
So maybe I would suggest having a new parameter (default as `hub-agent`) to choose a namespace for Traefik instead of removing the namespace in the DNS name.

2023-03-23 11:14 UTC, project0 commented on hub-agent/values.yaml
@youkoulayley it is more complicated, we have some defaults in the value what are difficult to template. For exmaple metricsURL, it is either configured (per default set) or when absent should not be used at all. So i cannot template the URL without introducing something to decide users enable with "default", custom or disable at all. 

I took another approach and just use `$POD_NAMESPACE` env var so it does not break anything.

2023-03-23 15:25 UTC, youkoulayley commented on hub-agent/values.yaml
Yeah, but you are not fixing the issue where the traefik is not installed in the same namespace.
Something like that works, but i's not very ... elegant let's say 😬: 
https://github.com/traefik/hub-helm-chart/compare/feat/tunnel-default-namespace...youkoulayley:hub-helm-chart:feat/tunnel-default-namespace?expand=1

2023-03-23 15:31 UTC, project0 commented on hub-agent/values.yaml
yes,and that is the problem. It changes significantly the way how to enable metrics gathering. Right now you can disabled it by omitting (or better setting it to a empty object), when we move to templates it requires additional logic and will introduce a breaking change. 

to make it more clear, we have currently two ways of a legit configuration: 
```traefik: {}```: disables metrics gathering in the controller
```traefik.metricsURL: "<URL>"```: enables and configure the traefik URL, it is currently enabled per default

Since i also learned that we may change the metrics integration anyway i am willing to just keep it that way before over engineering this part.

2023-03-23 15:35 UTC, project0 commented on hub-agent/values.yaml
to make it even worse, i would also not count on the existence of this specific service.

2023-03-27 12:07 UTC, youkoulayley commented on hub-agent/values.yaml
Maybe there is something I don't get, but, with my solution, there is no breaking change and you can still disable the metrics by not providing the URL.

Even if the metrics integration changes, we will still have the problem with the `tunnelHost` parameter. So why not tackle this right now?

2023-04-19 14:00 UTC, project0 commented
@youkoulayley i made some changes to include your suggestion around the namespace.

2023-04-19 14:06 UTC, mloiseleur commented on hub-agent/templates/deployment-tunnel.yaml
> +            - --traefik.tunnel-host={{ required "A valid .Values.tunnelDeployment.traefik.tunnelHost is required." .Values.tunnelDeployment.traefik.tunnelHost }}
```suggestion
            - --traefik.tunnel-host={{ .Values.tunnelDeployment.traefik.tunnelHost }}
```

2023-04-19 14:21 UTC, mloiseleur approved these changes
LGTM

2023-04-20 15:37 UTC, youkoulayley approved these changes

2023-04-27 13:34 UTC, merged