feat: Apply recommended security best practices
traefik/hub-helm-chart pull request #80
Opened 2023-03-23 09:29 UTC by project0

### What does this PR do?

* All deployments have strong default security context configured
* Ensure all deployments follow best practice with shared test

### Motivation

Increase trust of usage and better security defaults.

### More

- [x] Yes, I updated the tests accordingly
- [x] Yes, I ran `make test` and all the tests passed

2023-03-23 10:01 UTC, mloiseleur approved these changes
LVGTM

2023-03-27 08:11 UTC, youkoulayley requested changes

2023-03-27 08:11 UTC, youkoulayley commented on hub-agent/tests/__snapshot__/.empty
Why do we need to commit this directory?

2023-03-27 08:46 UTC, mloiseleur commented on hub-agent/tests/__snapshot__/.empty
Last version of helm-unittest needs a folder __ __snapshot__ __.

2023-03-27 08:51 UTC, tomMoulard commented on hub-agent/tests/__snapshot__/.empty
If it is just for testing purposes, what do you think about creating the folder when executing tests, and removing it from git ?

2023-03-27 09:02 UTC, mloiseleur commented on hub-agent/tests/__snapshot__/.empty
the alternative would be to a mount a tmpfs, see https://github.com/traefik/hub-helm-chart/pull/80/commits/d4ea7afbcc67f8ed3f4310e2a99d21050890e66c

2023-03-27 09:34 UTC, mloiseleur commented on hub-agent/tests/__snapshot__/.empty
@tomMoulard: Interesting idea. I will give it a try.

2023-03-27 09:40 UTC, mloiseleur commented on hub-agent/tests/__snapshot__/.empty
It works. Are we good, @youkoulayley ?

2023-03-27 09:57 UTC, youkoulayley approved these changes

2023-03-27 10:04 UTC, merged